name: Cypress End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start React App
        run: |
          cd $GITHUB_WORKSPACE
          npm run dev


       continue-on-error: false

      - name: Wait for React App
        run: sleep 25  

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6